export const quran = [
  {
    id: 5871,
    surah: "المطففين",
    aya: 23,
    textNoTashkeel: "على الأرائك ينظرون",
    textMinTashkeel: "عَلَى الأَرائِكِ يَنظُرونَ",
    textTashkeel: "عَلَى ٱلۡأَرَآئِكِ يَنظُرُونَ",
  },
  {
    id: 5872,
    surah: "المطففين",
    aya: 24,
    textNoTashkeel: "تعرف في وجوههم نضرة النعيم",
    textMinTashkeel: "تَعرِفُ فى وُجوهِهِم نَضرَةَ النَّعيمِ",
    textTashkeel: "تَعۡرِفُ فِي وُجُوهِهِمۡ نَضۡرَةَ ٱلنَّعِيمِ",
  },
  {
    id: 5873,
    surah: "المطففين",
    aya: 25,
    textNoTashkeel: "يسقون من رحيق مختوم",
    textMinTashkeel: "يُسقَونَ مِن رَحيقٍ مَختومٍ",
    textTashkeel: "يُسۡقَوۡنَ مِن رَّحِيقٖ مَّخۡتُومٍ",
  },
  {
    id: 5763,
    surah: "عبس",
    aya: 5,
    textNoTashkeel: "أما من استغنى",
    textMinTashkeel: "أَمّا مَنِ استَغنىٰ",
    textTashkeel: "أَمَّا مَنِ ٱسۡتَغۡنَىٰ",
  },
  {
    id: 5764,
    surah: "عبس",
    aya: 6,
    textNoTashkeel: "فأنت له تصدى",
    textMinTashkeel: "فَأَنتَ لَهُ تَصَدّىٰ",
    textTashkeel: "فَأَنتَ لَهُۥ تَصَدَّىٰ",
  },
  {
    id: 5765,
    surah: "عبس",
    aya: 7,
    textNoTashkeel: "وما عليك ألا يزكى",
    textMinTashkeel: "وَما عَلَيكَ أَلّا يَزَّكّىٰ",
    textTashkeel: "وَمَا عَلَيۡكَ أَلَّا يَزَّكَّىٰ",
  },
  {
    id: 5766,
    surah: "عبس",
    aya: 8,
    textNoTashkeel: "وأما من جاءك يسعى",
    textMinTashkeel: "وَأَمّا مَن جاءَكَ يَسعىٰ",
    textTashkeel: "وَأَمَّا مَن جَآءَكَ يَسۡعَىٰ",
  },
  {
    id: 5767,
    surah: "عبس",
    aya: 9,
    textNoTashkeel: "وهو يخشى",
    textMinTashkeel: "وَهُوَ يَخشىٰ",
    textTashkeel: "وَهُوَ يَخۡشَىٰ",
  },
  {
    id: 5768,
    surah: "عبس",
    aya: 10,
    textNoTashkeel: "فأنت عنه تلهى",
    textMinTashkeel: "فَأَنتَ عَنهُ تَلَهّىٰ",
    textTashkeel: "فَأَنتَ عَنۡهُ تَلَهَّىٰ",
  },
  {
    id: 5769,
    surah: "عبس",
    aya: 11,
    textNoTashkeel: "كلا إنها تذكرة",
    textMinTashkeel: "كَلّا إِنَّها تَذكِرَةٌ",
    textTashkeel: "كَلَّآ إِنَّهَا تَذۡكِرَةٞ",
  },
  {
    id: 5770,
    surah: "عبس",
    aya: 12,
    textNoTashkeel: "فمن شاء ذكره",
    textMinTashkeel: "فَمَن شاءَ ذَكَرَهُ",
    textTashkeel: "فَمَن شَآءَ ذَكَرَهُۥ",
  },
  {
    id: 5771,
    surah: "عبس",
    aya: 13,
    textNoTashkeel: "في صحف مكرمة",
    textMinTashkeel: "فى صُحُفٍ مُكَرَّمَةٍ",
    textTashkeel: "فِي صُحُفٖ مُّكَرَّمَةٖ",
  },
  {
    id: 5772,
    surah: "عبس",
    aya: 14,
    textNoTashkeel: "مرفوعة مطهرة",
    textMinTashkeel: "مَرفوعَةٍ مُطَهَّرَةٍ",
    textTashkeel: "مَّرۡفُوعَةٖ مُّطَهَّرَةِۭ",
  },
  {
    id: 5773,
    surah: "عبس",
    aya: 15,
    textNoTashkeel: "بأيدي سفرة",
    textMinTashkeel: "بِأَيدى سَفَرَةٍ",
    textTashkeel: "بِأَيۡدِي سَفَرَةٖ",
  },
  {
    id: 5774,
    surah: "عبس",
    aya: 16,
    textNoTashkeel: "كرام بررة",
    textMinTashkeel: "كِرامٍ بَرَرَةٍ",
    textTashkeel: "كِرَامِۭ بَرَرَةٖ",
  },
  {
    id: 5775,
    surah: "عبس",
    aya: 17,
    textNoTashkeel: "قتل الإنسان ما أكفره",
    textMinTashkeel: "قُتِلَ الإِنسٰنُ ما أَكفَرَهُ",
    textTashkeel: "قُتِلَ ٱلۡإِنسَٰنُ مَآ أَكۡفَرَهُۥ",
  },
  {
    id: 5776,
    surah: "عبس",
    aya: 18,
    textNoTashkeel: "من أي شيء خلقه",
    textMinTashkeel: "مِن أَىِّ شَيءٍ خَلَقَهُ",
    textTashkeel: "مِنۡ أَيِّ شَيۡءٍ خَلَقَهُۥ",
  },
  {
    id: 5777,
    surah: "عبس",
    aya: 19,
    textNoTashkeel: "من نطفة خلقه فقدره",
    textMinTashkeel: "مِن نُطفَةٍ خَلَقَهُ فَقَدَّرَهُ",
    textTashkeel: "مِن نُّطۡفَةٍ خَلَقَهُۥ فَقَدَّرَهُۥ",
  },
  {
    id: 5778,
    surah: "عبس",
    aya: 20,
    textNoTashkeel: "ثم السبيل يسره",
    textMinTashkeel: "ثُمَّ السَّبيلَ يَسَّرَهُ",
    textTashkeel: "ثُمَّ ٱلسَّبِيلَ يَسَّرَهُۥ",
  },
  {
    id: 5779,
    surah: "عبس",
    aya: 21,
    textNoTashkeel: "ثم أماته فأقبره",
    textMinTashkeel: "ثُمَّ أَماتَهُ فَأَقبَرَهُ",
    textTashkeel: "ثُمَّ أَمَاتَهُۥ فَأَقۡبَرَهُۥ",
  },
  {
    id: 5780,
    surah: "عبس",
    aya: 22,
    textNoTashkeel: "ثم إذا شاء أنشره",
    textMinTashkeel: "ثُمَّ إِذا شاءَ أَنشَرَهُ",
    textTashkeel: "ثُمَّ إِذَا شَآءَ أَنشَرَهُۥ",
  },
  {
    id: 5781,
    surah: "عبس",
    aya: 23,
    textNoTashkeel: "كلا لما يقض ما أمره",
    textMinTashkeel: "كَلّا لَمّا يَقضِ ما أَمَرَهُ",
    textTashkeel: "كَلَّا لَمَّا يَقۡضِ مَآ أَمَرَهُۥ",
  },
  {
    id: 5782,
    surah: "عبس",
    aya: 24,
    textNoTashkeel: "فلينظر الإنسان إلى طعامه",
    textMinTashkeel: "فَليَنظُرِ الإِنسٰنُ إِلىٰ طَعامِهِ",
    textTashkeel: "فَلۡيَنظُرِ ٱلۡإِنسَٰنُ إِلَىٰ طَعَامِهِۦٓ",
  },
  {
    id: 5783,
    surah: "عبس",
    aya: 25,
    textNoTashkeel: "أنا صببنا الماء صبا",
    textMinTashkeel: "أَنّا صَبَبنَا الماءَ صَبًّا",
    textTashkeel: "أَنَّا صَبَبۡنَا ٱلۡمَآءَ صَبّٗا",
  },
  {
    id: 5784,
    surah: "عبس",
    aya: 26,
    textNoTashkeel: "ثم شققنا الأرض شقا",
    textMinTashkeel: "ثُمَّ شَقَقنَا الأَرضَ شَقًّا",
    textTashkeel: "ثُمَّ شَقَقۡنَا ٱلۡأَرۡضَ شَقّٗا",
  },
  {
    id: 5785,
    surah: "عبس",
    aya: 27,
    textNoTashkeel: "فأنبتنا فيها حبا",
    textMinTashkeel: "فَأَنبَتنا فيها حَبًّا",
    textTashkeel: "فَأَنۢبَتۡنَا فِيهَا حَبّٗا",
  },
  {
    id: 5786,
    surah: "عبس",
    aya: 28,
    textNoTashkeel: "وعنبا وقضبا",
    textMinTashkeel: "وَعِنَبًا وَقَضبًا",
    textTashkeel: "وَعِنَبٗا وَقَضۡبٗا",
  },
  {
    id: 5787,
    surah: "عبس",
    aya: 29,
    textNoTashkeel: "وزيتونا ونخلا",
    textMinTashkeel: "وَزَيتونًا وَنَخلًا",
    textTashkeel: "وَزَيۡتُونٗا وَنَخۡلٗا",
  },
  {
    id: 5788,
    surah: "عبس",
    aya: 30,
    textNoTashkeel: "وحدائق غلبا",
    textMinTashkeel: "وَحَدائِقَ غُلبًا",
    textTashkeel: "وَحَدَآئِقَ غُلۡبٗا",
  },
  {
    id: 5789,
    surah: "عبس",
    aya: 31,
    textNoTashkeel: "وفاكهة وأبا",
    textMinTashkeel: "وَفٰكِهَةً وَأَبًّا",
    textTashkeel: "وَفَٰكِهَةٗ وَأَبّٗا",
  },
];
